/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        'page-bg': 'var(--color-page-bg)',
        'section-bg': 'var(--color-section-bg)',
        'search': 'var(--color-search)',
        'primary-text': 'var(--color-primary-text)',
        'secondary-text': 'var(--color-secondary-text)',
        'third-text': 'var(--color-third-text)',
        'secondary-btn': 'var(--color-secondary-btn)',
        'login-btn': 'var(--color-login-btn)',
        'logout-btn': 'var(--color-logout-btn)',
        'border': 'var(--color-border)',
        'hover-bg': 'var(--color-hover-bg)',
        'card-bg': 'var(--color-card-bg)',
        'card-border': 'var(--color-card-border)',
        'primary-btn': 'var(--color-primary-btn)',
        'submit-bg': 'var(--color-submit-bg)',
        'submit-text': 'var(--color-submit-text)',
        'accent': 'var(--color-accent)',
        'btn-text': 'var(--color-btn-text)',
        'dark-bg': 'var(--color-dark-bg)',
        'dark-btn': 'var(--color-dark-btn)',
      },
      backgroundColor: {
        'page-bg': 'var(--color-page-bg)',
        'section-bg': 'var(--color-section-bg)',
        'search': 'var(--color-search)',
        'secondary-btn': 'var(--color-secondary-btn)',
        'login-btn': 'var(--color-login-btn)',
        'logout-btn': 'var(--color-logout-btn)',
        'hover-bg': 'var(--color-hover-bg)',
        'card-bg': 'var(--color-card-bg)',
        'primary-btn': 'var(--color-primary-btn)',
        'submit-bg': 'var(--color-submit-bg)',
        'accent': 'var(--color-accent)',
        'dark-bg': 'var(--color-dark-bg)',
        'dark-btn': 'var(--color-dark-btn)',
      },
      textColor: {
        'primary-text': 'var(--color-primary-text)',
        'secondary-text': 'var(--color-secondary-text)',
        'third-text': 'var(--color-third-text)',
        'submit-text': 'var(--color-submit-text)',
        'btn-text': 'var(--color-btn-text)',
      },
      borderColor: {
        'border': 'var(--color-border)',
        'card-border': 'var(--color-card-border)',
        'section-bg': 'var(--color-section-bg)',
        'accent': 'var(--color-accent)',
      },
    },
  },
  plugins: [],
}
